<a href="https://colab.research.google.com/github/Satyam-003/Learn-Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy  The Beginning

[Numpy Official Documentation Link 😊](https://numpy.org/doc/stable/user/absolute_beginners.html#)

In [ ]:
# importing 'numpy' and giving it a nickname 'np'

import numpy as np


In [ ]:
# checking version of numpy

print(np.__version__)

2.0.2


In [ ]:
# Creating an array / vector / matrix

array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [ ]:
# creating zero or null vectors

null_vector =  np.zeros(4) # 4 is not an element. It's the size of the array.
print(null_vector)

[0. 0. 0. 0.]


In [ ]:
# Create a null vector of size 10
zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Array Fundamentals




In [ ]:
# accessing an Array element
a = np.array([1, 2, 3, 4, 5, 6])

#it is like list and strings start from 0 .

print(a[0])
print(a[0:])
print(a[::-1])
print(a[-6:-1])
print(a[0] == a[1])

# Array is mutable like list
a[0] = 10
print(a)

b = a[3:]
b[0] = 40
print(a)

big_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(big_array[1,3])


1
[1 2 3 4 5 6]
[6 5 4 3 2 1]
[1 2 3 4 5]
False
[10  2  3  4  5  6]
[10  2  3 40  5  6]
8


What is the difference b/w list and Array Slicing and Modification

In [ ]:
lst = [1,2,3,4,5,6]
b = lst[1:]
b[0]=90    # notice very carefully !(Modification happening)
print(b)
print(lst) # no change occur on main list

a = np.array([1, 2, 3, 4, 5, 6])
c = a[1:]
c[0]=90     # notice very carefully !(Modification happening)
print(c)
print(a)    # old array got updated with a new value

[90, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[90  3  4  5  6]
[ 1 90  3  4  5  6]


Array Attributes

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.ndim)

print(a.shape)  # 3 rows and 4 column   [1, 2, 3, 4]
                #                       [5, 6, 7, 8]
                #                       [9,10,11,12]

print(a.size)   # total no of elements in the array

print(a.dtype)  # int64 int for integer and 64 means 64-bit

# Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”.
# The data type is recorded in the dtype attribute.

2
(3, 4)
12
int64


How to create a Basic Array

In [ ]:
#This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()
a = np.zeros(4)
b = np.ones(4)
c = np.empty(2)
d = np.arange(4)
e = np.linspace(0,10,num=5)
print(a)
print(b)
print(c)
print(d)
print(e)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[4.9406565e-324 6.6416708e-310]
[0 1 2 3]
[ 0.   2.5  5.   7.5 10. ]


Adding, removing, and sorting element

In [ ]:
# This section covers np.sort(), np.concatenate()

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))
print('\n')
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12,13])
print(np.concatenate((a,b)))  # double brackets are necessary
print('\n')

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.concatenate((x,y)))  # double brackets are necessary
print('\n')
print((np.concatenate((x,y))).ndim)
print('\n')

# Advance method of concatenation
print("Advance method of concatenation")
print(np.concatenate((x,y), axis = 0))  # axis 0 : add rows
print('\n')
print(np.concatenate((x,y), axis = 1))  # axis 1 : add columns
print('\n')


# another example
p = np.array([[1,2],
              [3,4]])
q = np.array([[5],
              [6]])
print(np.concatenate((p,q), axis = 1))
print('\n')
print((np.concatenate((p,q), axis = 1)).ndim)
print('\n')
print((np.concatenate((p,q), axis = 1)).size)
print('\n')
print((np.concatenate((p,q), axis = 1)).shape)

# a good example
arrx = np.array([
    [
        [[1, 2], [3, 4], [5, 6]],
        [[7, 8], [9, 10], [11, 12]]
    ],
    [
        [[13, 14], [15, 16], [17, 18]],
        [[19, 20], [21, 22], [23, 24]]
    ]
])

[1 2 3 4 5 6 7 8]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


2


Advance method of concatenation
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


[[1 2 5]
 [3 4 6]]


2


6


(2, 3)


In [ ]:
print(arrx.ndim)
print(arrx.shape)
print(arrx.size)

4
(2, 2, 3, 2)
24


Reshaping an Array

In [ ]:
# This section covers arr.reshape()

a = np.array([[1,2,3,4,5,6]])
b = np.reshape(a,(3,2))
# print(a.shape)
print(b)
print('\n')
# With np.reshape, you can specify a few optional parameters:

print(np.reshape(a, (1,6), order='C'))
print('\n')
print(np.reshape(a, (1,6), order='F'))
print('\n')
print(np.reshape(a, (1,6), order='A'))

# don't panick those 'C','F','A' are just optional things it will generate same outputs
# for more deatils read the second comment attached to it .

(1, 6)
[[1 2]
 [3 4]
 [5 6]]


[[1 2 3 4 5 6]]


[[1 2 3 4 5 6]]


[[1 2 3 4 5 6]]


How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [ ]:
# This section covers np.newaxis, np.expand_dims

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print('\n')

# You can explicitly convert a 1D array to either a row vector or
# a column vector using np.newaxis. For example,

# you can convert a 1D array to a row vector by inserting an axis along the first dimension:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print('\n')

#  for a column vector, you can insert an axis along the second dimension:
column_vector = a[: ,np.newaxis]
print(column_vector)
print('\n')
print(column_vector.shape)
print('\n')


b = np.expand_dims(a, axis = 0)
c = np.expand_dims(a, axis = 1)
print(b.shape)
print(c.shape)

(6,)


(1, 6)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)


(1, 6)
(6, 1)


Indexing and Slicing

In [ ]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
print('\n')

five_up = (a > 5)
print(a[five_up])
print('\n')

divisible_by_2 = a[a%2==0]
print(divisible_by_2)
print('\n')

five_up = (a > 5) | (a == 5)
print(five_up)
print('\n')

b = np.nonzero(a < 5)
print(b)

[1 2 3 4]


[ 6  7  8  9 10 11 12]


[ 2  4  6  8 10 12]


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


How to create an array from existing data

In [ ]:
array = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = array[3:8]
print(arr1)

[4 5 6 7 8]


**Concept of hstack and vstak**

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
print(np.concatenate((a1,a2), axis=0))
print("\n")
print(np.vstack((a1, a2)))
print("\n")
print(np.concatenate((a1,a2), axis =1))
print("\n")
print(np.hstack((a1, a2)))


[[1 1]
 [2 2]
 [3 3]
 [4 4]]


[[1 1]
 [2 2]
 [3 3]
 [4 4]]


[[1 1 3 3]
 [2 2 4 4]]


[[1 1 3 3]
 [2 2 4 4]]


**hsplit**

In [ ]:
x = np.arange(1,25).reshape(2,12)
print(x)
print("\n")
# IF YOU WANTED TO SPLIT THIS ARRAY INTO THREE EQUALLY SHAPED ARRAYS '
a = np.hsplit(x,3)
print(a)
print("\n")
for a_s in a:
  print(a_s)
  print("\n")

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


[[ 1  2  3  4]
 [13 14 15 16]]


[[ 5  6  7  8]
 [17 18 19 20]]


[[ 9 10 11 12]
 [21 22 23 24]]




**BASIC ARRAY OPERATIONS **

In [ ]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a-b)
print (b**2)
print(10 * np.sin(a))

print("\n")
# Elementwise Product
a = np.array([[1,1],
              [0,1]])
b = np.array([[2,0],
              [3,4]])
print(a * b)

print("\n")
# Matrix multiplication
print(a@b)
# or
print(a.dot(b))

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


[[2 0]
 [0 4]]


[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
